export const ADDTOCART = "Add_TO_CART"
export const REMOVETOCART = "Remove_To_Cart"
export const EMPTYCART = "Empty_Cart"
export const PRODUCTLIST = "Product_List"
export const SETPRODUCTLIST = "Set_Product_List"